### ISSUE TITLE
bug: there is a problem pip installing getkey

### ISSUE THREAD

**Issue by thequackyduck** [wingkeet/getkey#1]
When I do: `pip install getkey`, it returns a error. This must be a bug with this module.

**Comment by wingkeet** [comment]
I did not publish my module to the Python Package Index, so `pip install getkey` would not work. If you want to use this module in your own project, you would have to `import` it.

**Comment by thequackyduck** [comment]
I did import it.

**Comment by wingkeet** [comment]
1. Make sure you `cd` into the directory where getkey.py is located.
2. Enter the Python shell and type the following commands:
```
$ python3
Python 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from getkey import getkey
>>> getkey()
(b'\x1bOP', 'f1')
>>>
```

**Comment by thequackyduck** [comment]
when I typed from getkey import getkey, it returned a error `ModuleNotFoundError: No module named 'getkey'`.

**Comment by wingkeet** [comment]
That means Python could not find the getkey.py file.
Did you download or clone the getkey.py file into your disk?

**Comment by thequackyduck** [comment]
ill figure it out.
